version: '2.1'
services:

  omero-data:
    container_name: omero-data
    image: hadim/omero-data:1.0.4
    command: "true"
    privileged: true
    volumes:
      - ${OMERO_DATA_DIR-../omero-data}:/data:Z

  omero-db:
    container_name: omero-db
    image: hadim/omero-db:1.0.4
    volumes_from:
      - omero-data
    environment:
      - PGDATA=/data/postgres

  omero-server:
    container_name: omero-server
    image: hadim/omero-server:1.0.4
    volumes_from:
      - omero-data
    links:
      - omero-db:omero-db
    ports:
      - "${OMERO_SERVER_PORT-4064}:4064"

  omero-web:
    container_name: omero-web
    image: hadim/omero-web:1.0.4
    volumes_from:
      - omero-data
    links:
      - omero-server:omero_server
    ports:
      - "${OMERO_WEB_PORT-80}:80"
      - "${OMERO_WEB_PORT_SSL-443}:443"
      - "${OMERO_WEB_PORT_DEVELOPMENT-4080}:4080"
    environment:
      - OMERO_WEB_USE_SSL=${OMERO_WEB_USE_SSL-yes}
      - OMERO_WEB_DEVELOPMENT=${OMERO_WEB_DEVELOPMENT-no}
