version: '2.1'
services:

  omero-data:
    container_name: omero-data
    build: omero-data
    command: "true"
    privileged: true
    volumes:
      - ${OMERO_DATA_DIR-../omero-data}:/data:Z

  omero-db:
    container_name: omero-db
    build: omero-db
    volumes_from:
      - omero-data
    environment:
      - PGDATA=/data/postgres

  omero-server:
    container_name: omero-server
    build: omero-server
    volumes_from:
      - omero-data
    links:
      - omero-db:omero-db
    ports:
      - "${OMERO_SERVER_PORT-4064}:4064"
